
def yields():
    for x in range(10):
        yield x

for x in yields():
    print(x)

"""

YIELD IT'S A "TYPE" OF RETURN THAT CONTROL BETTER THE MEMORY AND ARE SUPER USEFULL WHEN HAVE A LARGER DATASETS 

ONLY USE ONCE TIME IN THE CODE RUNS

IN CASE OF LOW CODES, SIMPLES, NEED TO USE MORE THAN 1 TIME, RETURNS IT'S A BETTER OPTION
IN CASE OF LARGER DATAS, AND USE ONCE TIME, YIELD IS BETTER
"""