var1= int(input('Digite um numero qualquer: '))
var2= int(input('Digite um segundo numero qualquer: '))
var3= int(input('Digite um terceiro numero qualquer: '))
var4= int(input('Digite um quarto numero qualquer: '))
print(f'a subtração de {var1} mais {var2} é igual a {var1-var2}')
print(f'a soma de {var1} mais {var2} é igual a {var1+var2}')
print(f'a divisão de {var1} mais {var2} é igual a {var1/var2}')
print(f'a multiplicação de {var1} mais {var2} é igual a {var1*var2}')
print(f'a soma de {var1+var2} menos a subtração {var4-var3} é igual a {(var1+var2)-(var4-var3)}')
